# ML Model Configuration
# Model-specific parameters and hyperparameters

# LSTM Model Configuration
lstm_model:
  architecture:
    sequence_length: 60
    num_features: 25
    layers:
      - type: "lstm"
        units: 128
        dropout: 0.2
        recurrent_dropout: 0.2
        return_sequences: true
      - type: "lstm" 
        units: 64
        dropout: 0.2
        recurrent_dropout: 0.2
        return_sequences: false
      - type: "dense"
        units: 32
        activation: "relu"
      - type: "dropout"
        rate: 0.3
      - type: "dense"
        units: 1
        activation: "linear"
        
  training:
    batch_size: 128
    epochs: 200
    learning_rate: 0.001
    optimizer: "adam"
    loss: "mse"
    metrics: ["mae", "mape"]
    
    # Early stopping
    early_stopping:
      monitor: "val_loss"
      patience: 20
      restore_best_weights: true
      
    # Learning rate scheduling
    lr_schedule:
      monitor: "val_loss"
      factor: 0.5
      patience: 10
      min_lr: 0.0001
      
  validation:
    split: 0.2
    shuffle: false  # Time series data
    
  prediction:
    sequence_stride: 1
    batch_prediction_size: 1000

# XGBoost Model Configuration
xgboost_model:
  parameters:
    objective: "reg:squarederror"
    n_estimators: 500
    max_depth: 8
    learning_rate: 0.05
    subsample: 0.8
    colsample_bytree: 0.8
    colsample_bylevel: 0.8
    reg_alpha: 0.1
    reg_lambda: 1.0
    random_state: 42
    
  training:
    # Early stopping
    early_stopping_rounds: 50
    eval_metric: "rmse"
    verbose_eval: 50
    
  feature_engineering:
    # Lag features
    lag_periods: [1, 2, 3, 5, 10, 20]
    
    # Rolling statistics
    rolling_windows: [5, 10, 20, 50]
    rolling_stats: ["mean", "std", "min", "max", "skew"]
    
    # Technical indicators as features
    technical_indicators:
      - "rsi_14"
      - "macd_signal"
      - "bb_position"
      - "stoch_k"
      - "williams_r"

# Random Forest Model Configuration  
random_forest_model:
  parameters:
    n_estimators: 300
    max_depth: 15
    min_samples_split: 10
    min_samples_leaf: 5
    max_features: "sqrt"
    bootstrap: true
    random_state: 42
    n_jobs: -1
    
  feature_selection:
    method: "importance_based"
    threshold: 0.01
    max_features: 50
    
# Ensemble Model Configuration
ensemble_model:
  # Model weights (initial)
  weights:
    lstm_model: 0.4
    xgboost_model: 0.35
    random_forest_model: 0.25
    
  # Ensemble strategy
  strategy: "weighted_average"  # or "stacking", "voting"
  
  # Dynamic weight adjustment
  weight_adjustment:
    enabled: true
    update_frequency: "daily"
    performance_window: 30  # days
    
  # Meta-learner (for stacking)
  meta_learner:
    type: "linear_regression"
    regularization: 0.01
    
  # Prediction confidence
  confidence_estimation:
    method: "prediction_interval"
    confidence_level: 0.95

# Model Performance Thresholds
performance_thresholds:
  # Minimum acceptable performance
  min_accuracy: 0.65
  min_precision: 0.60
  min_recall: 0.60
  min_f1_score: 0.60
  
  # Regression metrics
  max_mse: 0.05
  min_r2_score: 0.40
  max_mae: 0.15
  
  # Drift detection
  max_prediction_drift: 0.15
  max_feature_drift: 0.20
  
# Retraining Configuration
retraining:
  # Automatic retraining triggers
  triggers:
    performance_degradation: 0.10  # 10% drop in performance
    prediction_drift: 0.15
    data_drift: 0.20
    time_based: "weekly"  # Regular retraining schedule
    
  # Retraining parameters
  validation:
    holdout_size: 0.2
    time_series_split: true
    cross_validation_folds: 5
    
  # Model selection
  selection_criteria:
    primary: "val_r2_score"
    secondary: "val_mae"
    stability_weight: 0.3

# Feature Engineering
feature_engineering:
  # Price-based features
  price_features:
    returns: [1, 2, 5, 10, 20]  # Return periods
    log_returns: [1, 5, 10]
    volatility_windows: [5, 10, 20]
    
  # Volume-based features
  volume_features:
    volume_ratios: [5, 20]
    volume_moving_averages: [10, 20]
    on_balance_volume: true
    
  # Technical indicator features
  technical_features:
    rsi_periods: [9, 14, 21]
    macd_settings:
      fast: 12
      slow: 26
      signal: 9
    bollinger_bands:
      window: 20
      std_dev: 2
    moving_averages: [10, 20, 50, 200]
    
  # Market microstructure
  microstructure_features:
    bid_ask_spread: true
    order_flow_imbalance: false  # Requires Level 2 data
    price_impact: false
    
# Data Preprocessing
preprocessing:
  # Scaling
  scaling:
    method: "robust_scaler"  # Less sensitive to outliers
    feature_range: [-1, 1]
    
  # Missing value handling
  missing_values:
    strategy: "forward_fill"
    max_consecutive: 5
    
  # Outlier detection
  outlier_detection:
    method: "isolation_forest"
    contamination: 0.05
    
  # Feature selection
  feature_selection:
    method: "mutual_info_regression"
    k_best: 50