# Note: This is a template. In production, use proper secret management tools like:
# - Kubernetes Secrets with encryption at rest
# - External secret management (AWS Secrets Manager, HashiCorp Vault)
# - Sealed Secrets or External Secrets Operator

apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
  namespace: signal-trading
  labels:
    app: gateway-service
    component: security
type: Opaque
data:
  # Base64 encoded secrets (replace with actual values)
  jwt-secret: <JWT_SECRET_BASE64>  # echo -n "your-jwt-secret" | base64
  api-key: <API_KEY_BASE64>        # echo -n "your-api-key" | base64
  
---
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: signal-trading
  labels:
    component: database
    app: data-service
type: Opaque
data:
  # Database credentials (if using external database)
  username: <DB_USERNAME_BASE64>   # echo -n "username" | base64
  password: <DB_PASSWORD_BASE64>   # echo -n "password" | base64
  connection-string: <DB_CONN_BASE64>  # echo -n "connection-string" | base64

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: signal-trading
  labels:
    component: cache
    app: redis
type: Opaque
data:
  # Redis password (if authentication is enabled)
  password: <REDIS_PASSWORD_BASE64>  # echo -n "redis-password" | base64

---
# Service Account for microservices
apiVersion: v1
kind: ServiceAccount
metadata:
  name: signal-trading-sa
  namespace: signal-trading
  labels:
    app: signal-trading
    component: security

---
# Role for microservices
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: signal-trading
  name: signal-trading-role
  labels:
    app: signal-trading
    component: security
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]

---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: signal-trading-rolebinding
  namespace: signal-trading
  labels:
    app: signal-trading
    component: security
subjects:
- kind: ServiceAccount
  name: signal-trading-sa
  namespace: signal-trading
roleRef:
  kind: Role
  name: signal-trading-role
  apiGroup: rbac.authorization.k8s.io